task.settings:
  type: config_object
  label: 'Test settings'
  mapping:
    country:
      type: string
      label: 'Country name'
    city:
      type: string
      label: 'City name'
    timezone:
      type: string
      label: 'Selected timezone'
